name: Run Azure CLI Login with OpenID Connect
on: [push]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  test:
    environment: Azure # Specifices environment to access the secrets
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      env:
        Azure: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      uses: azure/login@v2
      with:
        client-id: ${{ env.Azure.clientId }}
        tenant-id: ${{ env.Azure.tenantId }}
        subscription-id: ${{ env.Azure.subscriptionId }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          # You can write your Azure CLI inline scripts here.
